import { db } from "@workspace/db";
import {
  usersTable, organizationsTable, orgMembersTable,
  serversTable, serverGroupsTable, templatesTable,
  deploymentsTable, deploymentLogsTable, deploymentStepsTable,
  monitoringAlertsTable, auditLogsTable, notificationsTable,
  aiConversationsTable, aiMessagesTable, documentsTable, reportsTable,
} from "@workspace/db";
import { eq } from "drizzle-orm";
import bcrypt from "bcryptjs";

const nginxSteps = [
  { order: 1, name: "Pre-flight check", command: "df -h && free -m && uptime", estimatedSeconds: 10 },
  { order: 2, name: "Update packages", command: "apt-get update -y", estimatedSeconds: 30 },
  { order: 3, name: "Install software", command: "apt-get install -y nginx", estimatedSeconds: 60 },
  { order: 4, name: "Configure SSL", command: "certbot --nginx -d example.com", estimatedSeconds: 120 },
  { order: 5, name: "Enable and start", command: "systemctl enable nginx && systemctl start nginx", estimatedSeconds: 10 },
  { order: 6, name: "Verify installation", command: "nginx -t && systemctl status nginx", estimatedSeconds: 10 },
];

const plan = {
  summary: "Automated deployment plan generated by Infrastructure Copilot AI",
  whyRequired: "Required to provision software on target server",
  benefits: ["Fully automated with rollback", "Pre-validated steps", "Complete audit trail"],
  risks: [{ description: "Brief service interruption", severity: "low", mitigation: "Schedule during off-peak hours" }],
  dependencies: ["Package repositories accessible", "Minimum 2GB disk space available"],
  estimatedDuration: 300, estimatedDowntime: 30,
  requiredPorts: [80, 443], requiredPackages: ["curl", "wget"],
  backupRecommendations: ["Take a VM snapshot before deployment"],
  rollbackStrategy: "Restore from pre-deployment snapshot or run uninstall script",
  expectedOutcome: "Software installed, configured, and running as a systemd service",
  steps: nginxSteps.map(s => ({ ...s, whyRequired: "Required for successful installation", rollbackCommand: `apt-get remove -y ${s.name}` })),
};

async function seed() {
  console.log("Seeding database...");

  // Users
  const pw = await bcrypt.hash("password123", 10);
  await db.insert(usersTable).values([
    { name: "Sarah Chen", email: "sarah@acme.com", passwordHash: pw },
    { name: "Mike Torres", email: "mike@acme.com", passwordHash: pw },
    { name: "Alex Kim", email: "alex@acme.com", passwordHash: pw },
    { name: "Jordan Lee", email: "jordan@acme.com", passwordHash: pw },
  ]).onConflictDoNothing();

  const users = await db.select().from(usersTable);
  const sarah = users.find(u => u.email === "sarah@acme.com")!;
  const mike = users.find(u => u.email === "mike@acme.com")!;
  const alex = users.find(u => u.email === "alex@acme.com")!;
  const jordan = users.find(u => u.email === "jordan@acme.com")!;

  // Organization
  await db.insert(organizationsTable).values({
    name: "Acme Corp",
    description: "Infrastructure engineering team managing production systems",
  }).onConflictDoNothing();

  const orgs = await db.select().from(organizationsTable);
  const org = orgs[0]!;

  // Members
  await db.insert(orgMembersTable).values([
    { orgId: org.id, userId: sarah.id, role: "engineer" },
    { orgId: org.id, userId: mike.id, role: "reviewer" },
    { orgId: org.id, userId: alex.id, role: "engineer" },
    { orgId: org.id, userId: jordan.id, role: "admin" },
  ]).onConflictDoNothing();

  // Server groups
  await db.insert(serverGroupsTable).values([
    { orgId: org.id, name: "Production", description: "Production infrastructure", color: "#ef4444" },
    { orgId: org.id, name: "Staging", description: "Staging environment", color: "#f59e0b" },
    { orgId: org.id, name: "Development", description: "Development servers", color: "#3b82f6" },
  ]).onConflictDoNothing();

  const groups = await db.select().from(serverGroupsTable).where(eq(serverGroupsTable.orgId, org.id));
  const pg = groups.find(g => g.name === "Production");
  const sg = groups.find(g => g.name === "Staging");
  const dg = groups.find(g => g.name === "Development");

  // Servers
  await db.insert(serversTable).values([
    { orgId: org.id, groupId: pg?.id ?? null, name: "prod-web-01", host: "10.0.1.10", sshPort: 22, sshUsername: "ubuntu", os: "ubuntu", osVersion: "24.04 LTS", status: "online", tags: ["web", "nginx"], description: "Primary web server", cpuUsage: 34, memUsage: 62, diskUsage: 45, lastSeen: new Date() },
    { orgId: org.id, groupId: pg?.id ?? null, name: "prod-db-01", host: "10.0.1.20", sshPort: 22, sshUsername: "ubuntu", os: "ubuntu", osVersion: "22.04 LTS", status: "online", tags: ["database", "postgresql"], description: "Primary PostgreSQL server", cpuUsage: 18, memUsage: 78, diskUsage: 67, lastSeen: new Date() },
    { orgId: org.id, groupId: sg?.id ?? null, name: "staging-app-01", host: "10.0.2.10", sshPort: 22, sshUsername: "ubuntu", os: "ubuntu", osVersion: "24.04 LTS", status: "online", tags: ["app", "docker"], description: "Staging app server", cpuUsage: 12, memUsage: 40, diskUsage: 28, lastSeen: new Date() },
    { orgId: org.id, groupId: pg?.id ?? null, name: "prod-cache-01", host: "10.0.1.30", sshPort: 22, sshUsername: "ubuntu", os: "ubuntu", osVersion: "22.04 LTS", status: "offline", tags: ["redis", "cache"], description: "Redis cache cluster node", lastSeen: new Date(Date.now() - 3600000) },
    { orgId: org.id, groupId: dg?.id ?? null, name: "dev-server-01", host: "10.0.3.10", sshPort: 22, sshUsername: "dev", os: "ubuntu", osVersion: "24.04 LTS", status: "online", tags: ["dev"], description: "Developer server", cpuUsage: 5, memUsage: 28, diskUsage: 15, lastSeen: new Date() },
  ]).onConflictDoNothing();

  const servers = await db.select().from(serversTable).where(eq(serversTable.orgId, org.id));
  const srv1 = servers.find(s => s.name === "prod-web-01")!;
  const srv2 = servers.find(s => s.name === "prod-db-01")!;
  const srv3 = servers.find(s => s.name === "staging-app-01")!;
  const srv4 = servers.find(s => s.name === "prod-cache-01")!;
  const srv5 = servers.find(s => s.name === "dev-server-01")!;

  // Built-in templates
  await db.insert(templatesTable).values([
    { orgId: null, name: "Nginx Latest", software: "nginx", version: "1.28.0", category: "webserver", description: "Latest stable Nginx with SSL and reverse proxy support", osRequirements: ["ubuntu", "debian"], steps: nginxSteps, configValues: {}, envVars: {}, postInstallActions: ["systemctl enable nginx"], isBuiltIn: true, usageCount: 42 },
    { orgId: null, name: "PostgreSQL 16", software: "postgresql", version: "16.3", category: "database", description: "Enterprise PostgreSQL with replication and backup", osRequirements: ["ubuntu", "debian", "rhel"], steps: nginxSteps, configValues: {}, envVars: {}, postInstallActions: [], isBuiltIn: true, usageCount: 38 },
    { orgId: null, name: "Docker CE", software: "docker", version: "27.1.1", category: "container", description: "Docker Container Engine with Compose and BuildKit", osRequirements: ["ubuntu", "debian"], steps: nginxSteps, configValues: {}, envVars: {}, postInstallActions: ["usermod -aG docker ubuntu"], isBuiltIn: true, usageCount: 55 },
    { orgId: null, name: "Redis 7.4", software: "redis", version: "7.4.0", category: "database", description: "In-memory data structure store with cluster support", osRequirements: ["ubuntu", "debian"], steps: nginxSteps, configValues: {}, envVars: {}, postInstallActions: [], isBuiltIn: true, usageCount: 29 },
    { orgId: null, name: "Node.js 22 LTS", software: "nodejs", version: "22.0.0", category: "language", description: "Node.js JavaScript runtime with npm and yarn", osRequirements: ["ubuntu", "debian"], steps: nginxSteps, configValues: {}, envVars: {}, postInstallActions: [], isBuiltIn: true, usageCount: 31 },
    { orgId: null, name: "MySQL 8.4", software: "mysql", version: "8.4.0", category: "database", description: "MySQL Community Server with InnoDB storage", osRequirements: ["ubuntu", "debian", "rhel"], steps: nginxSteps, configValues: {}, envVars: {}, postInstallActions: [], isBuiltIn: true, usageCount: 22 },
    { orgId: null, name: "Java 21 LTS", software: "java", version: "21.0.4", category: "language", description: "OpenJDK 21 with Maven and Gradle", osRequirements: ["ubuntu", "debian"], steps: nginxSteps, configValues: {}, envVars: {}, postInstallActions: [], isBuiltIn: true, usageCount: 18 },
    { orgId: null, name: "Apache HTTPD 2.4", software: "apache2", version: "2.4.62", category: "webserver", description: "Apache HTTP Server with mod_ssl and mod_rewrite", osRequirements: ["ubuntu", "debian"], steps: nginxSteps, configValues: {}, envVars: {}, postInstallActions: [], isBuiltIn: true, usageCount: 11 },
    { orgId: null, name: "Prometheus + Grafana", software: "prometheus", version: "2.54.0", category: "monitoring", description: "Prometheus metrics with Grafana dashboards", osRequirements: ["ubuntu", "debian"], steps: nginxSteps, configValues: {}, envVars: {}, postInstallActions: [], isBuiltIn: true, usageCount: 16 },
  ]).onConflictDoNothing();

  const tmpls = await db.select().from(templatesTable);
  const nginxTmpl = tmpls.find(t => t.software === "nginx")!;
  const pgTmpl = tmpls.find(t => t.software === "postgresql")!;
  const dockerTmpl = tmpls.find(t => t.software === "docker")!;
  const redisTmpl = tmpls.find(t => t.software === "redis")!;

  // Deployments
  await db.insert(deploymentsTable).values([
    { orgId: org.id, serverId: srv1.id, templateId: nginxTmpl.id, name: "Nginx 1.28 Production Deploy", description: "Upgrade Nginx to latest stable on prod-web-01", status: "completed", createdById: sarah.id, approvedById: mike.id, approvalComment: "Approved - tested in staging first", plan: plan as any, configOverrides: {}, startedAt: new Date(Date.now() - 7200000), completedAt: new Date(Date.now() - 6900000), duration: 300 },
    { orgId: org.id, serverId: srv3.id, templateId: pgTmpl.id, name: "PostgreSQL 16 Install", description: "Fresh PostgreSQL 16 installation on staging", status: "awaiting_approval", createdById: sarah.id, plan: plan as any, configOverrides: {} },
    { orgId: org.id, serverId: srv5.id, templateId: dockerTmpl.id, name: "Docker CE Installation", description: "Install Docker container runtime on dev server", status: "running", createdById: alex.id, approvedById: jordan.id, plan: plan as any, configOverrides: {}, startedAt: new Date(Date.now() - 600000) },
    { orgId: org.id, serverId: srv4.id, templateId: redisTmpl.id, name: "Redis Cache Cluster Setup", description: "Deploy Redis 7.4 cluster node on prod-cache-01", status: "failed", createdById: sarah.id, approvedById: mike.id, plan: plan as any, configOverrides: {}, startedAt: new Date(Date.now() - 172800000), completedAt: new Date(Date.now() - 172500000), duration: 180 },
  ]).onConflictDoNothing();

  const deps = await db.select().from(deploymentsTable).where(eq(deploymentsTable.orgId, org.id));
  const dep1 = deps.find(d => d.status === "completed");

  if (dep1) {
    await db.insert(deploymentLogsTable).values([
      { deploymentId: dep1.id, level: "info", message: "Starting deployment: Nginx 1.28 Production Deploy", stepName: null },
      { deploymentId: dep1.id, level: "info", message: "SSH connection established to prod-web-01", stepName: "Pre-flight check" },
      { deploymentId: dep1.id, level: "success", message: "Pre-flight check passed: 45GB disk, 2.1GB memory free", stepName: "Pre-flight check" },
      { deploymentId: dep1.id, level: "info", message: "Running: apt-get update -y", stepName: "Update packages" },
      { deploymentId: dep1.id, level: "success", message: "Package index updated successfully", stepName: "Update packages" },
      { deploymentId: dep1.id, level: "info", message: "Running: apt-get install -y nginx", stepName: "Install software" },
      { deploymentId: dep1.id, level: "success", message: "Nginx 1.28.0 installed successfully", stepName: "Install software" },
      { deploymentId: dep1.id, level: "success", message: "SSL certificate configured for example.com", stepName: "Configure SSL" },
      { deploymentId: dep1.id, level: "success", message: "Nginx enabled and started", stepName: "Enable and start" },
      { deploymentId: dep1.id, level: "success", message: "Verification passed: nginx/1.28.0 running on port 80,443", stepName: "Verify installation" },
      { deploymentId: dep1.id, level: "info", message: "Deployment completed successfully in 5m 0s", stepName: null },
    ]).onConflictDoNothing();

    await db.insert(deploymentStepsTable).values(
      nginxSteps.map((step, i) => ({
        deploymentId: dep1.id,
        order: step.order,
        name: step.name,
        command: step.command,
        status: "completed" as const,
        duration: step.estimatedSeconds,
        output: `Step completed successfully in ${step.estimatedSeconds}s`,
        startedAt: new Date(Date.now() - (7200 - i * 50) * 1000),
        completedAt: new Date(Date.now() - (7200 - (i + 1) * 50) * 1000),
      }))
    ).onConflictDoNothing();
  }

  // Monitoring alerts
  await db.insert(monitoringAlertsTable).values([
    { orgId: org.id, serverId: srv2.id, type: "memory_high", severity: "warning", message: "Memory usage at 78% — approaching 80% threshold", resolved: false },
    { orgId: org.id, serverId: srv4.id, type: "unreachable", severity: "critical", message: "Server unreachable — SSH connection timeout after 30s", resolved: false },
    { orgId: org.id, serverId: srv1.id, type: "ssl_expiring", severity: "warning", message: "SSL certificate for prod-web-01 expires in 14 days", resolved: false },
  ]).onConflictDoNothing();

  // Audit logs
  await db.insert(auditLogsTable).values([
    { orgId: org.id, userId: sarah.id, action: "server_registered", resourceType: "server", resourceId: srv1.id, resourceName: "prod-web-01", details: { host: "10.0.1.10" }, ipAddress: "10.0.0.1" },
    { orgId: org.id, userId: sarah.id, action: "deployment_created", resourceType: "deployment", resourceId: dep1?.id ?? 1, resourceName: "Nginx 1.28 Production Deploy", details: {}, ipAddress: "10.0.0.1" },
    { orgId: org.id, userId: mike.id, action: "deployment_approved", resourceType: "deployment", resourceId: dep1?.id ?? 1, resourceName: "Nginx 1.28 Production Deploy", details: { comment: "Approved" }, ipAddress: "10.0.0.5" },
    { orgId: org.id, userId: sarah.id, action: "deployment_executed", resourceType: "deployment", resourceId: dep1?.id ?? 1, resourceName: "Nginx 1.28 Production Deploy", details: {}, ipAddress: "10.0.0.1" },
    { orgId: org.id, userId: jordan.id, action: "member_added", resourceType: "user", resourceId: alex.id, resourceName: "Alex Kim", details: { role: "engineer" }, ipAddress: "10.0.0.7" },
    { orgId: org.id, userId: sarah.id, action: "server_registered", resourceType: "server", resourceId: srv5.id, resourceName: "dev-server-01", details: { host: "10.0.3.10" }, ipAddress: "10.0.0.1" },
  ]).onConflictDoNothing();

  // Notifications
  await db.insert(notificationsTable).values([
    { userId: sarah.id, type: "deployment_completed", title: "Deployment Completed", message: "Nginx 1.28 Production Deploy completed successfully on prod-web-01", read: false, link: "/deployments/1" },
    { userId: sarah.id, type: "approval_required", title: "Approval Required", message: "PostgreSQL 16 Install on staging-app-01 awaiting your approval", read: false, link: "/deployments/2" },
    { userId: sarah.id, type: "server_alert", title: "Server Alert", message: "prod-cache-01 is unreachable — requires immediate attention", read: true, link: "/monitoring" },
    { userId: mike.id, type: "approval_required", title: "Approval Required", message: "PostgreSQL 16 Install awaiting approval", read: false, link: "/deployments/2" },
  ]).onConflictDoNothing();

  // AI conversation sample
  const [conv] = await db.insert(aiConversationsTable).values({
    orgId: org.id, userId: sarah.id,
    title: "How to install Nginx with SSL on Ubuntu 24.04?",
    lastMessageAt: new Date(Date.now() - 3600000),
  }).onConflictDoNothing().returning();

  if (conv) {
    await db.insert(aiMessagesTable).values([
      { conversationId: conv.id, role: "user", content: "How do I install Nginx with SSL on Ubuntu 24.04?" },
      { conversationId: conv.id, role: "assistant", content: "I'll guide you through installing Nginx with SSL on Ubuntu 24.04.\n\n**Step 1: Install Nginx**\n```bash\napt-get update -y\napt-get install -y nginx\n```\n\n**Step 2: Install Certbot**\n```bash\napt-get install -y certbot python3-certbot-nginx\n```\n\n**Step 3: Obtain SSL certificate**\n```bash\ncertbot --nginx -d yourdomain.com\n```\n\nCertbot will automatically modify your Nginx config for HTTPS. Would you like me to create a deployment template for this?" },
    ]).onConflictDoNothing();
  }

  // Documents
  await db.insert(documentsTable).values([
    { orgId: org.id, type: "deployment_report", title: "Nginx 1.28 Production Deploy — Report", content: "# Deployment Report\n\n**Status:** Completed Successfully\n**Duration:** 5 minutes\n**Server:** prod-web-01\n\n## Summary\nNginx 1.28.0 was successfully installed and configured with SSL.", format: "markdown", relatedDeploymentId: dep1?.id ?? null, relatedServerId: srv1.id },
    { orgId: org.id, type: "sop", title: "Standard Nginx Deployment Procedure", content: "# SOP: Nginx Deployment\n\n## Overview\nThis document outlines the standard procedure for deploying Nginx.\n\n## Steps\n1. Pre-flight check\n2. Package update\n3. Installation\n4. SSL configuration\n5. Service verification", format: "markdown" },
    { orgId: org.id, type: "architecture_doc", title: "Production Infrastructure Architecture", content: "# Architecture Overview\n\nOur production infrastructure runs across 3 server groups...", format: "markdown" },
  ]).onConflictDoNothing();

  // Reports
  await db.insert(reportsTable).values([
    { orgId: org.id, type: "deployment_summary", title: "Weekly Deployment Summary — July 2026", summary: "4 deployments executed this week. 75% success rate. 1 approval pending.", data: JSON.stringify({ total: 4, succeeded: 3, failed: 1, successRate: 75 }) },
    { orgId: org.id, type: "security_scan", title: "Monthly Security Report — July 2026", summary: "SSL certificates checked, 1 expiring in 14 days. All servers scanned.", data: JSON.stringify({ serversScanned: 5, issuesFound: 1 }) },
  ]).onConflictDoNothing();

  console.log("✓ Seed complete!");
}

seed().catch(console.error).finally(() => process.exit(0));
